language: elixir

elixir:
  - 1.7
otp_release: 21

matrix:
  include:
    - elixir: 1.4
      otp_release: 18
    - elixir: 1.5
      otp_release: 19
    - elixir: 1.6
      otp_release: 20

script:
  - mix test
  - mix dialyzer
